/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;


import EDD.*;
import static EDD.Tree.construirTree;
import Principal.Persona;
import arbol.genealogico.Visualizador;
import javax.swing.JOptionPane;

/**
 *
 * @author VictorB
 */
public class Menu extends javax.swing.JFrame {
     static TablaHash hashTablePrincipal;
    private Tree arbolPrincipal;
    private ListaEnlazada listaPersonas;
    /**
     * Creates new form Menu
     */
    public Menu(ListaEnlazada listaPersonas) {
        this.listaPersonas=listaPersonas;
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void mostrarArbol() {
        if (listaPersonas == null || listaPersonas.estaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay datos para mostrar el árbol.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Construir el árbol genealógico y mostrarlo
        Tree arbolGenealogico = construirTree(listaPersonas); // Método que construye el árbol
        Visualizador visualizador = new Visualizador(arbolGenealogico); // Visualizador del árbol
        visualizador.construirGrafo(); // Mostrar el árbol
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Carga = new javax.swing.JButton();
        VerRegistro = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Carga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Carga.setText("Cargar Familia ");
        Carga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargaActionPerformed(evt);
            }
        });

        VerRegistro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VerRegistro.setText("Ver Registro ");
        VerRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerRegistroActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("jButton4");

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");

        Salir.setText("X");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VerRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Carga, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(Carga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VerRegistro)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargaActionPerformed
                                    
    // Reiniciar la lista de personas (borrar los datos previamente cargados)
    ListaEnlazada listaPersonas = new ListaEnlazada(); // Crear una nueva instancia para eliminar cualquier dato previo

    Json reader = new Json(); // Instancia de la clase Reader
    listaPersonas = reader.Read(); // Carga la información del archivo JSON

    if (listaPersonas != null) {
        // Muestra las personas en un área de texto, tabla, o consola
        StringBuilder resultado = new StringBuilder();
        Nodo nodoActual = listaPersonas.getCabeza();

        // Obtener el apellido de la primera persona (si existe)
        String apellidoCasa = "";
        if (nodoActual != null) {
            Persona primeraPersona = (Persona) nodoActual.getDato();
            apellidoCasa = primeraPersona.obtenerApellido();
        }

        while (nodoActual != null) {
            Persona persona = (Persona) nodoActual.getDato(); // Obtén el objeto Persona
            resultado.append(persona.toString()).append("\n");
            nodoActual = nodoActual.getSiguiente();
        }

        // Mostrar resultado en consola
        System.out.println("Personas cargadas desde el archivo JSON:");
        

        System.out.println(resultado.toString());
    }
  
    }//GEN-LAST:event_CargaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SalirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void VerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerRegistroActionPerformed
                                        
    // Verificar si el árbol genealógico existe
    // Verificar si el árbol genealógico existe y tiene una raíz
     
        // Construir y visualizar el árbol
        mostrarArbol();
    
    }//GEN-LAST:event_VerRegistroActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carga;
    private javax.swing.JButton Salir;
    private javax.swing.JButton VerRegistro;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
